package org.SmartWaste.repository;



import com.google.cloud.Timestamp;
import com.google.cloud.firestore.CollectionReference;
import com.google.cloud.firestore.Firestore;
import com.google.cloud.firestore.WriteResult;
import com.google.firebase.cloud.FirestoreClient;
import org.SmartWaste.Tasks;
import org.springframework.stereotype.Repository;


import java.util.Date;
import java.util.List;
import java.util.concurrent.ExecutionException;


@Repository
public class TasksRepository
{
    private final Firestore firestore = FirestoreClient.getFirestore();
    private final CollectionReference tasksCollection = firestore.collection("tasks");


    public String submitTask(Tasks task) throws ExecutionException, InterruptedException
    {
        String autoGeneratedId = tasksCollection.document().getId();
        task.setTask_id(autoGeneratedId);
        task.setAssigned(false);
        task.setTimestamp(Timestamp.now());
        WriteResult result = tasksCollection.document(autoGeneratedId).set(task).get();
        return "Task published successfully at: " + result.getUpdateTime();
    }

    public List<Tasks> getUnassigned() throws ExecutionException, InterruptedException
    {
        List<Tasks> unassigned = tasksCollection
                .whereEqualTo("assigned", false)
                .get()
                .get()
                .toObjects(Tasks.class);
        return unassigned;
    }
}
